### ISSUE TITLE
Bug: 1.20.1 Version cannot load correctly on DEDICATED_SERVER

### ISSUE THREAD

**Issue by GLDYM** [KasugaLibGroup/KasugaLib#15]
### Describe the bug

KasugaLib 1.20.1 Version cannot load correctly on DEDICATED_SERVER.

### Steps to reproduce

Put create-1.20.1-0.5.1.j & kasuga_lib-1.20.1-nightly-create-241123-ed024d1 into a 47.3.7 forge server and setup it.

### Expected behavior

The server should load correctly.

### Logs

https://mclo.gs/t5MYapI

### Versions

- OS: Windows 11 (amd64) version 10.0
- Java Version: 21.0.1, BellSoft
- Minecraft Version: 1.20.1
- KasugaLib version: Build from https://github.com/KasugaLibGroup/KasugaLib/commit/ed024d1bbe603baaedce887e77df2b414014de57

### Additional context

Why here init a MENU? A client judgement should be put here.

https://github.com/KasugaLibGroup/KasugaLib/blob/ed024d1bbe603baaedce887e77df2b414014de57/src/main/java/kasuga/lib/core/KasugaLibStacks.java#L81

**Comment by TimeBather** [comment]
> Why here init a MENU? A client judgement should be put here.

The menu should init here. The Menu System is used to sync datas between the GUI system and server side. The real problem is it calls `TargetsClient.register();` in "GuiMenuManager.java", which not allowed in dedicated server side.
https://github.com/KasugaLibGroup/KasugaLib/blob/aee3899d18cc43920ce47fad7dc0f61da9e338a6/src/main/java/kasuga/lib/core/menu/GuiMenuManager.java#L24

I'll fix it today. Thank you for your reporting.

**Comment by TimeBather** [comment]
There is still some issue with the dist DEDICATED_SERVER caused by the `FluidReg`. It should fix by @MegumiKasuga .
```
java.lang.ExceptionInInitializerError: null
	at kasuga.lib.KasugaLib.<init>(KasugaLib.java:38) ~[%23211!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.2.jar%23207!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.2.jar%23210!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.2.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at kasuga.lib.example_env.AllExampleElements.<clinit>(AllExampleElements.java:150) ~[%23211!/:?] {re:classloading}
```
Related code:
https://github.com/KasugaLibGroup/KasugaLib/blob/aee3899d18cc43920ce47fad7dc0f61da9e338a6/src/main/java/kasuga/lib/example_env/AllExampleElements.java#L150
